CREATE DATABASE  STUDENTS_DB;
USE STUDENTS_DB;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USERS (
  USERNAME varchar(35) PRIMARY KEY,
  PASSWD varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_ROLES (
  USERNAME varchar(35) NOT NULL,
  ROLE varchar(35) NOT NULL,
  UNIQUE KEY UNIQUE_INDEX (USERNAME, ROLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PICTURES;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS BADGESS;

CREATE TABLE STUDENTS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  STUDENT_ID int(7) NOT NULL,
  LAST_NAME varchar(35) NOT NULL,
  FIRST_NAME varchar(35) NOT NULL,
  BIRTH_DATE varchar(35) NOT NULL,
  PHONE_NUMBER varchar(14) NOT NULL,
  NUMBER VARCHAR(255), 
  CITY VARCHAR(255), 
  STREET VARCHAR(255), 
  POSTAL_CODE VARCHAR(255), 
  PRIMARY KEY (ID),
  UNIQUE KEY UNIQUE_INDEX_NAME (LAST_NAME,FIRST_NAME,BIRTH_DATE),
  UNIQUE KEY UNIQUE_INDEX_STUDENT_ID (STUDENT_ID)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;



CREATE TABLE PICTURES (
  ID int (11) NOT NULL AUTO_INCREMENT,
  STUDENT_ID int(11),
  PICTURE longblob,
  PRIMARY KEY (ID),
  CONSTRAINT FK_PICTURES_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

